export default playersDummy = {
  get: "players/squads",
  parameters: {
    team: "2598",
  },
  errors: [],
  results: 1,
  paging: {
    current: 1,
    total: 1,
  },
  response: [
    {
      team: {
        id: 2598,
        name: "Petrolul Ploiesti",
        logo: "https://media-1.api-sports.io/football/teams/2598.png",
      },
      players: [
        {
          id: 42765,
          name: "G. Gavrilaş",
          age: 33,
          number: 1,
          position: "Goalkeeper",
          photo: "https://media-3.api-sports.io/football/players/42765.png",
        },
        {
          id: 42764,
          name: "M. Eşanu",
          age: 25,
          number: 12,
          position: "Goalkeeper",
          photo: "https://media-2.api-sports.io/football/players/42764.png",
        },
        {
          id: 324930,
          name: "A. Jercălău",
          age: 18,
          number: 35,
          position: "Goalkeeper",
          photo: "https://media-3.api-sports.io/football/players/324930.png",
        },
        {
          id: 30948,
          name: "L. Zima",
          age: 29,
          number: 38,
          position: "Goalkeeper",
          photo: "https://media-2.api-sports.io/football/players/30948.png",
        },
        {
          id: 16108,
          name: "Marian Huja",
          age: 24,
          number: 2,
          position: "Defender",
          photo: "https://media-1.api-sports.io/football/players/16108.png",
        },
        {
          id: 37578,
          name: "B. Meijers",
          age: 26,
          number: 3,
          position: "Defender",
          photo: "https://media-1.api-sports.io/football/players/37578.png",
        },
        {
          id: 50084,
          name: "P. Papp",
          age: 34,
          number: 4,
          position: "Defender",
          photo: "https://media-3.api-sports.io/football/players/50084.png",
        },
        {
          id: 42569,
          name: "V. Țicu",
          age: 23,
          number: 5,
          position: "Defender",
          photo: "https://media-1.api-sports.io/football/players/42569.png",
        },
        {
          id: 50222,
          name: "I. Latovlevici",
          age: 37,
          number: 14,
          position: "Defender",
          photo: "https://media-1.api-sports.io/football/players/50222.png",
        },
        {
          id: 65365,
          name: "G. Pashov",
          age: 33,
          number: 26,
          position: "Defender",
          photo: "https://media-3.api-sports.io/football/players/65365.png",
        },
        {
          id: 234653,
          name: "Garutti",
          age: 29,
          number: 34,
          position: "Defender",
          photo: "https://media-2.api-sports.io/football/players/234653.png",
        },
        {
          id: 404526,
          name: "S. Doua",
          age: 22,
          number: 71,
          position: "Defender",
          photo: "https://media-3.api-sports.io/football/players/404526.png",
        },
        {
          id: 41717,
          name: "Pedro Justiniano",
          age: 23,
          number: null,
          position: "Defender",
          photo: "https://media-2.api-sports.io/football/players/41717.png",
        },
        {
          id: 61971,
          name: "Jefferson",
          age: 29,
          number: 6,
          position: "Midfielder",
          photo: "https://media-3.api-sports.io/football/players/61971.png",
        },
        {
          id: 28539,
          name: "G. Grozav",
          age: 33,
          number: 7,
          position: "Midfielder",
          photo: "https://media-2.api-sports.io/football/players/28539.png",
        },
        {
          id: 55320,
          name: "Jair",
          age: 29,
          number: 8,
          position: "Midfielder",
          photo: "https://media-3.api-sports.io/football/players/55320.png",
        },
        {
          id: 44383,
          name: "C. Budescu",
          age: 34,
          number: 10,
          position: "Midfielder",
          photo: "https://media-2.api-sports.io/football/players/44383.png",
        },
        {
          id: 72368,
          name: "T. Seto",
          age: 37,
          number: 11,
          position: "Midfielder",
          photo: "https://media-3.api-sports.io/football/players/72368.png",
        },
        {
          id: 40504,
          name: "S. Hanca",
          age: 31,
          number: 20,
          position: "Midfielder",
          photo: "https://media-1.api-sports.io/football/players/40504.png",
        },
        {
          id: 46058,
          name: "S. Purtić",
          age: 25,
          number: 25,
          position: "Midfielder",
          photo: "https://media-3.api-sports.io/football/players/46058.png",
        },
        {
          id: 401556,
          name: "Juan Andres Pătrașcu",
          age: 19,
          number: 36,
          position: "Midfielder",
          photo: "https://media-3.api-sports.io/football/players/401556.png",
        },
        {
          id: 367688,
          name: "M. Rădulescu",
          age: 18,
          number: 41,
          position: "Midfielder",
          photo: "https://media-2.api-sports.io/football/players/367688.png",
        },
        {
          id: 367689,
          name: "M. Ioniță",
          age: 16,
          number: 43,
          position: "Midfielder",
          photo: "https://media-2.api-sports.io/football/players/367689.png",
        },
        {
          id: 43307,
          name: "L. Dumitriu",
          age: 31,
          number: 44,
          position: "Midfielder",
          photo: "https://media-2.api-sports.io/football/players/43307.png",
        },
        {
          id: 3239,
          name: "I. Diomandé",
          age: 31,
          number: 82,
          position: "Midfielder",
          photo: "https://media-3.api-sports.io/football/players/3239.png",
        },
        {
          id: 136246,
          name: "M. Constantinescu",
          age: 21,
          number: 95,
          position: "Midfielder",
          photo: "https://media-3.api-sports.io/football/players/136246.png",
        },
        {
          id: 42571,
          name: "M. Bratu",
          age: 21,
          number: 98,
          position: "Midfielder",
          photo: "https://media-1.api-sports.io/football/players/42571.png",
        },
        {
          id: 307497,
          name: "A. Musi",
          age: 19,
          number: 99,
          position: "Midfielder",
          photo: "https://media-3.api-sports.io/football/players/307497.png",
        },
        {
          id: 309892,
          name: "A. Boțogan",
          age: 19,
          number: null,
          position: "Midfielder",
          photo: "https://media-3.api-sports.io/football/players/309892.png",
        },
        {
          id: 41896,
          name: "C. Irobiso",
          age: 30,
          number: 9,
          position: "Attacker",
          photo: "https://media-1.api-sports.io/football/players/41896.png",
        },
        {
          id: 356687,
          name: "I. Răducan",
          age: 18,
          number: 13,
          position: "Attacker",
          photo: "https://media-1.api-sports.io/football/players/356687.png",
        },
        {
          id: 66844,
          name: "Z. Petrović",
          age: 26,
          number: 17,
          position: "Attacker",
          photo: "https://media-1.api-sports.io/football/players/66844.png",
        },
        {
          id: 127332,
          name: "R. Bucur",
          age: 21,
          number: 24,
          position: "Attacker",
          photo: "https://media-2.api-sports.io/football/players/127332.png",
        },
        {
          id: 381697,
          name: "I. Cojocaru",
          age: 20,
          number: 77,
          position: "Attacker",
          photo: "https://media-2.api-sports.io/football/players/381697.png",
        },
        {
          id: 324272,
          name: "Z. Mitrov",
          age: 21,
          number: 93,
          position: "Attacker",
          photo: "https://media-3.api-sports.io/football/players/324272.png",
        },
      ],
    },
  ],
};
